### ISSUE TITLE
Better ruleset delete handling

### ISSUE THREAD

**Issue by lcorrigall** [unchartedsoftware/PLUTO#76]
Should mark rulesets deleted if they have been used in runs, handle issues of creation with the same name (e.g. newer version), etc.

**Comment by Maunique** [comment]
Seeing an error when linking to run of a deleted ruleset.

**Comment by lcorrigall** [comment]
Should be fixed now

**Comment by Maunique** [comment]
Deleted a ruleset then selected Details for a rrun of it. Edit Ruleset link not greyed out. Select the link and get an error message. Not fixed.

**Comment by Maunique** [comment]
Can now create a ruleset with the same name as a deleted one.
